import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {
    AccordionModule,
    AutoCompleteModule,
    BlockUIModule, BreadcrumbModule,
    ButtonModule,
    CalendarModule, CarouselModule, ChartModule,
    CheckboxModule,
    ChipsModule, CodeHighlighterModule, ColorPickerModule,
    ConfirmDialogModule, ContextMenuModule,
    DropdownModule, EditorModule,
    FileUploadModule, FullCalendarModule, GalleriaModule, InplaceModule,
    InputMaskModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    KeyFilterModule, LightboxModule,
    MegaMenuModule, MenubarModule, MenuModule,
    MessageModule,
    MessagesModule,
    MultiSelectModule, OrderListModule,
    OrganizationChartModule,
    OverlayPanelModule, PaginatorModule, PanelMenuModule,
    PanelModule, PasswordModule,
    PickListModule, ProgressBarModule,
    RadioButtonModule, RatingModule,
    ScrollPanelModule,
    SelectButtonModule, SlideMenuModule, SliderModule,
    SpinnerModule,
    SplitButtonModule,
    TabMenuModule, TerminalModule, TieredMenuModule, ToastModule,
    ToggleButtonModule,
    ToolbarModule,
    TooltipModule,
    TreeTableModule,
    TriStateCheckboxModule, VirtualScrollerModule
} from 'primeng/primeng';
import {TranslateModule} from '@ngx-translate/core';
import {DateFormatPipe} from './date/date-format.pipe';
import {DateTimeFormatPipe} from './date/date-time-format.pipe';
import {ParaComponent} from './para/para.component';
import {CardModule} from 'primeng/card';
import {ParaFormatPipe} from './para/para-format.pipe';
import {TableModule} from 'primeng/table';
import {EnumPipe} from './utils/enum.pipe';
import {DialogModule} from 'primeng/dialog';
import {TabViewModule} from 'primeng/tabview';
import {TreeModule} from 'primeng/tree';
import {DataViewModule} from 'primeng/dataview';
import {StepsModule} from 'primeng/steps';
import {ListboxModule} from 'primeng/listbox';
import {FieldsetModule} from 'primeng/fieldset';
import {StringWrapperPipe} from './utils/string-wrapper.pipe';
import {ValidationMessageComponent} from "./validation-message/validation-message.component";

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        ReactiveFormsModule,
        InputTextModule,
        ButtonModule,
        PanelModule,
        TabViewModule,
        DropdownModule,
        InputSwitchModule,
        MultiSelectModule,
        TreeModule,
        ToggleButtonModule,
        CardModule,
        OverlayPanelModule,
        SplitButtonModule,
        TableModule,
        InputTextareaModule,
        BlockUIModule,
        TranslateModule,
        ConfirmDialogModule,
        MessageModule,
        MessagesModule,
        TooltipModule,
        AccordionModule,
        CalendarModule,
        AutoCompleteModule,
        KeyFilterModule,
        SpinnerModule,
        DialogModule,
        InputMaskModule,
        FileUploadModule,
        DataViewModule,
        StepsModule,
        ListboxModule,
        FieldsetModule,
        CheckboxModule,
        TriStateCheckboxModule,
        MegaMenuModule,
        OrganizationChartModule,
        TreeTableModule,
        TabMenuModule,
        SelectButtonModule,
        EditorModule,
        PickListModule,
        ChipsModule,
        BreadcrumbModule,
        CarouselModule,
        ChartModule,
        CodeHighlighterModule,
        ColorPickerModule,
        ContextMenuModule,
        FullCalendarModule,
        GalleriaModule,
        InplaceModule,
        LightboxModule,
        MenuModule,
        MenubarModule,
        OrderListModule,
        PaginatorModule,
        PanelMenuModule,
        PasswordModule,
        ProgressBarModule,
        RatingModule,
        SlideMenuModule,
        SliderModule,
        TerminalModule,
        TieredMenuModule,
        ToastModule,
        VirtualScrollerModule
    ],
    providers: [],
    declarations: [
        DateFormatPipe,
        DateTimeFormatPipe,
        ParaFormatPipe,
        EnumPipe,
        StringWrapperPipe,
        ParaComponent,
        ValidationMessageComponent
    ],
    exports: [
        DateFormatPipe,
        EnumPipe,
        StringWrapperPipe,
        SpinnerModule,
        DateTimeFormatPipe,
        ParaFormatPipe,
        CommonModule,
        CardModule,
        FormsModule,
        ReactiveFormsModule,
        InputTextModule,
        InputTextareaModule,
        ButtonModule,
        PanelModule,
        DropdownModule,
        BlockUIModule,
        InputSwitchModule,
        MultiSelectModule,
        TreeModule,
        TabViewModule,
        TooltipModule,
        AccordionModule,
        ToggleButtonModule,
        OverlayPanelModule,
        SplitButtonModule,
        TableModule,
        ConfirmDialogModule,
        TranslateModule,
        MessageModule,
        MessagesModule,
        CalendarModule,
        AutoCompleteModule,
        ParaComponent,
        KeyFilterModule,
        DialogModule,
        InputMaskModule,
        FileUploadModule,
        TabViewModule,
        DataViewModule,
        StepsModule,
        FieldsetModule,
        ListboxModule,
        CheckboxModule,
        TriStateCheckboxModule,
        MegaMenuModule,
        OrganizationChartModule,
        TreeTableModule,
        TabMenuModule,
        ScrollPanelModule,
        SelectButtonModule,
        PickListModule,
        RadioButtonModule,
        ToolbarModule,
        ChipsModule,
        BreadcrumbModule,
        CarouselModule,
        ChartModule,
        CodeHighlighterModule,
        ColorPickerModule,
        ContextMenuModule,
        EditorModule,
        FullCalendarModule,
        GalleriaModule,
        InplaceModule,
        LightboxModule,
        MenuModule,
        MenubarModule,
        OrderListModule,
        PaginatorModule,
        PanelMenuModule,
        PasswordModule,
        ProgressBarModule,
        RatingModule,
        SlideMenuModule,
        SliderModule,
        TerminalModule,
        TieredMenuModule,
        ToastModule,
        VirtualScrollerModule,
        ValidationMessageComponent
    ]
})
export class SharedModule {
}
